### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Kolobok12309** [kouts/vuepress-plugin-vue-example#15]
After 50 version of vuepress, their use esm modules [link](https://github.com/vuepress/vuepress-next/blob/main/CHANGELOG.md#breaking-changes-4) and is not worked with `vuepress-plugin-vue-example`

```
(node:54649) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54649) UnhandledPromiseRejectionWarning: /Users/foobar/projects/shared-front/node_modules/vuepress-plugin-vue-example/src/index.js:1
import { getDirname, path } from '@vuepress/utils'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async loadUserConfig (file:///Users/foobar/projects/shared-front/node_modules/@vuepress/cli/dist/index.js:77:18)
    at async CAC.dev (file:///Users/foobar/projects/shared-front/node_modules/@vuepress/cli/dist/index.js:460:52)
(node:54649) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54649) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/Users/foobar/projects/shared-front/node_modules/vuepress-plugin-vue-example/src/index.js:1
import { getDirname, path } from '@vuepress/utils'
^^^^^^
```

This code fix it
```json
// package.json
"type": "module"
```

**Comment by kouts** [comment]
Thanks for the heads up @Kolobok12309, I have pushed a new version can you check if that fixes it?

**Comment by Kolobok12309** [comment]
> Thanks for the heads up @Kolobok12309, I have pushed a new version [v2.0.7](https://github.com/kouts/vuepress-plugin-vue-example/tree/v2.0.7) can you check if that fixes it?

Sorry for long answer, everything is fine
https://codesandbox.io/s/vuepress-plugin-vue-example-2-0-4-uv6i17?file=/README.md
